run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - vendor
    - .git

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unused
    - errcheck
    - gosimple
    - staticcheck
  disable-all: false

linters-settings:
  goimports:
    local-prefixes: github.com/denysvitali/openhands-runtime-go

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck